Updates to match coding conventions

diff --git a/scripts/unit-test b/scripts/unit-test
--- a/scripts/unit-test
+++ b/scripts/unit-test
@@ -13,6 +13,6 @@ done
 
 if [[ $errors > 0 ]]
 then
-	echo "$errors unit test(s) failed" >&2
+    echo "$errors unit test(s) failed" >&2
     exit $errors
 fi
